image: python2.7
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  report_card: {}
script:
- pip install -r test/requirements.txt
- python setup.py develop && python setup.py test
